{% set name = "pyMapVBVD" %}
{% set version = "0.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/06/ca/21db8a0269881444a69f9ccf9aa4a0415c50d456db914d5d0a851f5a809b/pymapvbvd-0.6.1.tar.gz
  sha256: 1238259d9d979f35edd4ff6667467d48f4246aa98a50e17b3c4c97b2c105fbb5

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python >=3.9
    - pip
    - versioneer
    - pyyaml
  host:
    - python {{ python_min }}
    - pip
    - pyyaml
    - versioneer
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy >=1.26
    - tqdm
    - scipy >=1.13
    - six

test:
  requires:
    - python {{ python_min }}
  imports:
    - mapvbvd

about:
  home: https://github.com/wexeee/pymapvbvd
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python port of mapVBVD.
  description: |
    Python port of mapVBVD.
  doc_url: https://github.com/wexeee/pymapvbvd
  dev_url: https://github.com/wexeee/pymapvbvd

extra:
  recipe-maintainers:
    - wtclarke
