{% set name = "pyMapVBVD" %}
{% set version = "0.5.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b34abbada1ee2512176818e912f1238a8fff8679fc938eb38fe8d60a8d3401f0

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python >=3.7
    - pip
    - versioneer
    - pyyaml
  host:
    - python >=3.7
    - pip
    - pyyaml
    - versioneer
  run:
    - python >=3.7
    - numpy
    - tqdm
    - scipy
    - six

test:
  imports:
    - mapvbvd

about:
  home: https://github.com/wexeee/pymapvbvd
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python port of mapVBVD.
  description: |
    Python port of mapVBVD.
  doc_url: https://github.com/wexeee/pymapvbvd
  dev_url: https://github.com/wexeee/pymapvbvd

extra:
  recipe-maintainers:
    - wtclarke
