{% set name = "pyMapVBVD" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/92/12/835aab5795d0d63958774b83a86eaa0dcbb4c92d92641b18c3a7abdcbb7d/pymapvbvd-{{ version }}.tar.gz
  sha256: 0968e50e334f0a79271e80e65559abd9559772789a810427b7119ef6e961c356

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python >=3.9
    - pip
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=77
    - setuptools-scm >=8
  run:
    - python >={{ python_min }}
    - numpy >=1.26
    - tqdm
    - scipy >=1.13
    - six
    - matplotlib-base
    - h5py
test:
  requires:
    - python {{ python_min }}
  imports:
    - mapvbvd

about:
  home: https://github.com/wexeee/pymapvbvd
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python port of mapVBVD.
  description: |
    Python port of mapVBVD.
  doc_url: https://github.com/wexeee/pymapvbvd
  dev_url: https://github.com/wexeee/pymapvbvd

extra:
  recipe-maintainers:
    - vkarlaftis
    - wtclarke
