{% set name = "pyMapVBVD" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8d03b3e8fb30e5a5b309d3be79dee64b0c511297f62f0b78bc089ed1a4e21e57

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python >=3.9
    - pip
    - versioneer
    - pyyaml
  host:
    - python >=3.9
    - pip
    - pyyaml
    - versioneer
  run:
    - python >=3.9
    - numpy
    - tqdm
    - scipy
    - six

test:
  imports:
    - mapvbvd

about:
  home: https://github.com/wexeee/pymapvbvd
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python port of mapVBVD.
  description: |
    Python port of mapVBVD.
  doc_url: https://github.com/wexeee/pymapvbvd
  dev_url: https://github.com/wexeee/pymapvbvd

extra:
  recipe-maintainers:
    - wtclarke
